name: Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
env: 
  CON: init string
jobs:
  check: 
    name: CheckDB
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: apt update && apt-get install mysql-client -y
      - name: Run 
        run: mysql --user=${{secrets.DB_USER}} --password=${{secrets.DB_PASSWORD}} --host=${{secrets.DB_HOST}} -e "SELECT 'key' FROM rapter.Cache;"
      
            
