name: Cypress Tests

on: pull_request

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: pnpm build
      - name:
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: dist
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build folder
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          start: pn start
          parallel: true
          record: true
        env:
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
